### ISSUE TITLE
Gold doesn't buy me anything from the trader?

### ISSUE THREAD

**Issue by nivilack** [Kenan2000/BL9#1]
So I downloaded BL9 (I enjoy it thoroughly) but I have like 6000+ gold and every time I try to buy something the trader will ask for the same set amount. For example, I ask to buy the BL9 survivor boots, and the trader says is "That'll be 12Gcomb" is that another currency I haven't found yet? Or could something be stopping him from giving me more than just the starting gear? (I was able to get the starting pistol and soldering iron but nothing after that.) Also I just updated to the latest version of the mod

**Comment by Kenan2000** [comment]
@nivilack you need to craft GComb and PComb - Gold Combination coins and Platinum Combination coins - I've done this to avoid extra inventory lag from having thousands of gold and platinum, you are automatically provided with the recipe, check it out and tell me if you have any more issues :-)

Oh and new melee weapons recipes require fabrication and mechanics of level 5, just so you know, to make it balanced, you automatically unlock them, so keep your eye on the recipes :-)

**Comment by nivilack** [comment]
Oh alright thank you! XD I'll go try it now
