### ISSUE TITLE
Invalid enum string

### ISSUE THREAD

**Issue by Elmerald** [Kenan2000/BL9#14]
I've been using the most recent iOS version of cdda (0.E-3). Any suggestions?

DEBUG    : Error: Invalid enum string 'leg_r' for '9body_part'

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : /Users/apollov/work/CDDA-new/CDDA/Libraries/Cataclysm-DDA/src/main_menu.cpp
 LINE     : 781

**Comment by Kenan2000** [comment]
@Elmerald Use version from my Modpack here https://github.com/Kenan2000/CDDA-Kenan-Modpack/releases/tag/Modpack_0_E3_Version, it works well, if you have any other issues or problems, just post an issue and I'll hopefully look into it
