### ISSUE TITLE
BL9 100% Res

### ISSUE THREAD

**Issue by Nephelos** [Kenan2000/BL9#15]
Got the following bug while try to create a character 

DEBUG    : Could not find an iexamine function matching 'cardreader'!

 FUNCTION : void (* iexamine_function_from_string(const string&))(player&, const tripoint&)
 FILE     : src/iexamine.cpp
 LINE     : 6224
 VERSION  : 6616372

Experimental version (Build 2021 07 04 1015/Version 6616372 (tiles))

**Comment by Kenan2000** [comment]
Here, https://github.com/Kenan2000/BL9/commit/ed93c7ab089cf4f591890caeb41a60603e236c53, this hopefully fixes it

**Comment by Nephelos** [comment]
Thanks, that was fast :) I love your modpack keep up the great work. (This comment is approved by the Mi-Go Friendship Society❤)
