### ISSUE TITLE
BL9 Pre Nested/Bright Nights - Cannot Load BL9 Soldering Iron - Fix Included

### ISSUE THREAD

**Issue by DrPariah** [Kenan2000/BL9#2]
The Nested Containers pocket data format prevents the item from being reloaded. I just updated the thing using the format of the basic soldering iron, and confirmed that it does work in game. This also might cause some issues with the BL9 firearms, as I was having a wonky time trying to load/unload the BL9 infused 9mm, but will need to look into that further.

FIX: Just copy/paste this over the BL9 Soldering Iron entry for the Pre-Nested/Bright Nights version(s).

{
		"id": "BL9_repair_soldering",
		"looks_like": "soldering_iron",
		"type": "TOOL",
		"name": {
			"str": "BL9-infused soldering iron"
		},
		"description": "A soldering iron that has somehow been infused with the entirely sentient BL9 that somehow mentally communicates with you, it is covered and entirely reinforced with it's thick tissue with multiple spiky almost unnoticeabely vibrating protrusions that give it a more intimidating, animate look, ",
		"weight": "281 g",
		"volume": "785 ml",
		"price": 1000,
		"price_postapoc": 100,
		"bashing": 2,
		"cutting": 6,
		"material": ["iron", "BL9"],
		"symbol": "%",
		"color": "light_gray",
		"ammo": ["battery"],
		"charges_per_use": 1,
		"use_action": [{
				"type": "repair_item",
				"item_action_type": "repair_metal",
				"materials": ["BL9", "BL9_mk2", "BL9_mk2_mid1", "BL9_mk2_mid2", "BL9_mid1", "BL9_mid2", "steel", "plastic"],
				"skill": "fabrication",
				"cost_scaling": 0.15,
				"move_cost": 845
			},
			{
				"flame": false,
				"type": "cauterize"
			}
		],
		"flags": ["SPEAR", "BELT_CLIP", "ALLOWS_REMOTE_USE"],
		"magazines": [
			[
				"battery",
				[
					"light_minus_battery_cell",
					"light_battery_cell",
					"light_plus_battery_cell",
					"light_atomic_battery_cell",
					"light_minus_atomic_battery_cell",
					"light_minus_disposable_cell",
					"light_disposable_cell"
				]
			]
		],
		"magazine_well": 1
	}
]

**Comment by Kenan2000** [comment]
Fixed :-) , thank you so much!
