### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by Setmaster** [Kenan2000/BL9#23]
` DEBUG    : Error: Json error: C:/Users/prime/Documents/Catapult/dda/userdata/mods/BL9-100%_monster_resilience_version/Furniture-Terrain/terrain.json:707:23: expected string but got '{'

    "move_cost": 0,
    "flags": [ "NOITEM", "CONNECT_TO_WALL" ],
    "examine_action": {
                      ^

      "type": "cardreader",
      "flags": [ "SCIENCE_CARD" ],

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 865
 VERSION  : 0.F-3
`

**Comment by Kenan2000** [comment]
@Setmaster Hmm, first of all, I do not maintain mods for any stable versions of game, I honestly try to maintain them for latest experimental versions, second is this error is from older versions of my mod which I have fixed, do not install or update mods using any launchers, install all mods manually using GitHub, it is more reliable, more safe hopefully as well
