### ISSUE TITLE
Island base hangar generation error

### ISSUE THREAD

**Issue by Xayrlen** [Kenan2000/BL9#24]
**Describe the bug**
Every time I include this mod into the world I get an error with a hangar before character creation. It happens every time regardless of mod orders.
Here's the row of messages I receive:

![1234](https://user-images.githubusercontent.com/86978521/215863187-fcaea4ba-0bfa-4594-bcd6-582264927289.png)
![1245](https://user-images.githubusercontent.com/86978521/215863194-a308781a-97f6-46e7-8118-d2ac76792b88.png)
![123456](https://user-images.githubusercontent.com/86978521/215863201-ea1e1c4d-0bed-4828-8f2f-ba7e9c4ac487.png)

Vehicle placement varies every time, however, it's the same error every time you try to run the world with this mod.

**Steps to reproduce**

1. Create a new world;
2. Add BL9-100% mod to the list and create world;
3. Create a new character on the same world.

**Versions and configuration**

- OS: Windows 10 Pro, 22H2, 19045.2486;
- Game Version: 03f25dc [64-bit];
- Graphics Version: Tiles;
- Game Language: English;
- Mods loaded:
![123](https://user-images.githubusercontent.com/86978521/215864228-e3b62b55-b861-403b-863b-3c6e5e1e94b3.png)

**Comment by Kenan2000** [comment]
@Xayrlen Hopefully fixed in this update as well
