### ISSUE TITLE
[DDA] healing_resting renamed to healing_multiplier and its purpose adjusted

### ISSUE THREAD

**Issue by nemesis688** [Kenan2000/BL9#25]
This pull: https://github.com/CleverRaven/Cataclysm-DDA/pull/63836 changed how healing asleep/awake worked/meant.

**Comment by Kenan2000** [comment]
@nemesis688 Hopefully fixed in this update as well

**Comment by Kenan2000** [comment]
@nemesis688 I initially made this update slightly incorrectly in terms of healing rate stats essentially. I've hopefully fixed this in this update as well
