### ISSUE TITLE
Obsolete Flags

### ISSUE THREAD

**Issue by arvay5** [Kenan2000/BL9#26]
DEBUG    : The "STAB" flag used on BL9_stun_pike is obsolete. Add a "stab" value in the "melee_damage" object instead.

 FUNCTION : finalize_pre
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_factory.cpp
 LINE     : 254
 VERSION  : 48ed876

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
