### ISSUE TITLE
Missing mandatory member "bash_resist"

### ISSUE THREAD

**Issue by MrXen0morph** [Kenan2000/BL9#28]
![image](https://user-images.githubusercontent.com/55456465/236572041-ff49ff55-150c-4a3b-af56-65ba75531d05.png)

**Comment by MrXen0morph** [comment]
[debug.log](https://github.com/Kenan2000/BL9/files/11410222/debug.log)

**Comment by Kenan2000** [comment]
You play on an older game version which is either latest stable game version or some older experimental version. I try to update my BL9 mod only for latest experimental versions of this game version so you need to download latest experimental versions if you honestly want to play with my BL9 mod hopefully as well

**Comment by MrXen0morph** [comment]
> You play on an older game version which is either latest stable game version or some older experimental version. I try to update my BL9 mod only for latest experimental versions of this game version so you need to download latest experimental versions if you honestly want to play with my BL9 mod hopefully as well

Okay, is there a way to download a previous release in some way? I'm on 0.G, latest stable.

**Comment by Kenan2000** [comment]
Hmm, when you get bored of playing on latest stable download latest experimental. I try to maintain mods only for latest experimental versions hopefully as well
