### ISSUE TITLE
Old json settings for materials

### ISSUE THREAD

**Issue by 9ghtX** [Kenan2000/BL9#29]
On 0.G CDDA version BL9 throws fatal error with wrong materials' resist. It seems like devs changed json structure so you need to change it, otherwise mod won't load.

```
DEBUG    : Error: Json error: C:/Games/Cataclysm DDA/dda/userdata/mods/BL9-100%_monster_resilience_version/material_types.json:1:2: missing mandatory member "bash_resist"

[
 ^
  {
    "type": "material",
    "id": "BL9",


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 986
 VERSION  : d6ec466
```

**Comment by KeenEye333** [comment]
[material_types.zip](https://github.com/Kenan2000/BL9/files/12026261/material_types.zip)

I had the same issue on 0.G. I have fixed it. Here is the zip file, simply extract and replace the file into your BL9 mod directory.

> On 0.G CDDA version BL9 throws fatal error with wrong materials' resist. It seems like devs changed json structure so you need to change it, otherwise mod won't load.
> 
> ```
> DEBUG    : Error: Json error: C:/Games/Cataclysm DDA/dda/userdata/mods/BL9-100%_monster_resilience_version/material_types.json:1:2: missing mandatory member "bash_resist"
> 
> [
>  ^
>   {
>     "type": "material",
>     "id": "BL9",
> 
> 
>  FUNCTION : bool main_menu::new_character_tab()
>  FILE     : src/main_menu.cpp
>  LINE     : 986
>  VERSION  : d6ec466
> ```

**Comment by Kenan2000** [comment]
@9ghtX Hello there, I suggest you to join Russian discord server https://discord.gg/Hu4KWYYCZD where I will try to answer your questions hopefully as well

**Comment by Kenan2000** [comment]
@9ghtX With regards to CDDA version of my BL9 mod I try to update at the same time maintain my BL9 mod hopefully only for latest experimental versions so if you want to play with my BL9 mod you need to download CDDA latest experimental versions
