### ISSUE TITLE
Color tags

### ISSUE THREAD

**Issue by Humsas** [Kenan2000/BL9#30]
There are quite many color tags that are missing close bracket ">". You can see them with this link https://github.com/search?q=repo%3AKenan2000%2FBL9%20%3C%2Fcolor%22&type=code

**Comment by Kenan2000** [comment]
@Humsas I really appreciate you messaging me with this, but compared to other lots of renovations, fixes which I try to make for my BL9 mod this color typo thing is very negligible honestly
