### ISSUE TITLE
'N'has no terrain,furniture,or other definition

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/BL9#31]
Seems you forgot to define it in this update
![image](https://github.com/Kenan2000/BL9/assets/22638873/1243b7a1-ff70-4e2c-807e-06a0173ad68d)

**Comment by waveyl** [comment]
warnings for type BL9_stun_claws_mk2: unknown technique tec_krav_maga_counter
 warnings for type BL9_stun_claws_mk3: unknown technique tec_krav_maga_counter

**Comment by waveyl** [comment]
item pickle could not be put in container jar_glass_sealed when spawning item group item pickle within BL9_enemy_food: not enough space.  This can be resolved either by changing the container or contents to ensure that they fit, or by specifying an overflow behaviour via "on_overflow" on the item group.

**Comment by waveyl** [comment]
invalid furniture id "f_robotic_assembler" 
Removed in #68108

**Comment by Kenan2000** [comment]
@waveyl Hopefully fixed in this update as well
