### ISSUE TITLE
Character creation loading error

### ISSUE THREAD

**Issue by B1ight** [Kenan2000/BL9#34]
DEBUG    : Error: Json error: C:/Users/simon/Desktop/CDDA/dda/userdata/mods/BL9-100%_monster_resilience_version/material_types.json:1:2: missing mandatory member "bash_resist"

[
 ^
  {
    "type": "material",
    "id": "BL9",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 986
 VERSION  : d6ec466

**Comment by Kenan2000** [comment]
My BL9 mod for CDDA version is not compatible with stable versions of CDDA but only with experimental versions so if you want to play with it you need to play on latest experimental versions hopefully
